apiVersion: v1
kind: Service
metadata:
  name: uppercase-rsocket
  labels:
    app: uppercase-rsocket
    component: uppercase-rsocket
    type: streaming-spike
spec:
  ports:
    - port: 7000
      name: uppercase-rsocket-port
      targetPort: 7000
      protocol: TCP
  selector:
    app: uppercase-rsocket
    component: uppercase-rsocket