spring:
  cloud:
    stream:
      bindings:
        proxy-in-0:
          destination: dataIn
          binder: kafka
        proxy-out-0:
          destination: dataOut
          binder: rabbit
    function:
        definition: proxy
        grpc.port: 55554
management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"
