apiVersion: v1
kind: Service
metadata:
  name: aggregate-multibinder-rsocket
  labels:
    app: aggregate-multibinder-rsocket
    component: aggregate-multibinder-rsocket
    type: streaming-spike
    spring-deployment-id: aggregate-multibinder-rsocket
spec:
  type: LoadBalancer
  ports:
    - port: 81
      name: aggregate-multibinder-rsocket
      targetPort: 8080
      protocol: TCP
  selector:
    app: aggregate-with-multibinder-rsocket
    component: aggregate-with-multibinder-rsocket